### PR TITLE
Update to 0.5.23.1

### PR DESCRIPTION
**Pull request by frol**

### CODE REVIEW

**Comment by frol** [comment]
@jakirkham Hi! Could you please help to understand the Circle CI error:

```
TEST END: nuitka-0.5.23.1-py27_0
INFO:/opt/conda/lib/python3.5/site-packages/conda_build/config.py:--keep-old-work flag not specified.  Removing source and build files.

# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /feedstock_root/build_artefacts/linux-64/nuitka-0.5.23.1-py27_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 104, in main
    exists = built_distribution_already_exists(cli, meta, owner)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 24, in built_distribution_already_exists
    fname = bldpkg_path(meta)
TypeError: bldpkg_path() missing 1 required positional argument: 'config'
```

**Comment by jakirkham** [comment]
Please [re-render]( https://github.com/conda-forge/conda-smithy/blob/master/README.md#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.4.2`. Optionally try the `-c`/`--commit` argument to commit the `re-rendering`.

**Comment by jakirkham** [comment]
Please add `setuptools` as a build requirement if you need it. Alternatively you could drop `--single-version-externally-managed --record record.txt`.

**Comment by frol** [comment]
@jakirkham Aha, I have just added it. Let's see...

**Comment by jakirkham** [comment]
Yep, looks like that was it.

If you did use the `-c`/`--commit` argument with re-rendering, I would really appreciate your feedback. Just put in that feature last night. 😄

**Comment by frol** [comment]
@jakirkham I did use it! It is super friendly, I expected much more tweaking... Thank you!

**Comment by jakirkham** [comment]
That's great news! Was hoping this would help make things easier. 😄

If you do come across any issues though, please don't hesitate to raise an issue over at the [`conda-smithy` issue tracker]( https://github.com/conda-forge/conda-smithy/issues ). As it is pretty new, I wouldn't be surprised if we have a few kinks that need to be worked out.

**Pull request merged**
